export const blogPostsMeta = [
  {
    id: 1,
    title: "Bl 1001",
    excerpt: "## What is git? {#What-is-git}\n\nGit is a version control system which is maintained on your local system. Git gives us a...",
    date: "2025-01-01",
    readTime: "2 min read",
    category: "General",
  },
  {
    id: 2,
    title: "Bl 1002",
    excerpt: "## Client Side Rendering {#Client-Side-Rendering}\n\n![Client Side Rendering](/BL-1002/csr.png)\n\nWhen we talk about client...",
    date: "2025-01-01",
    readTime: "4 min read",
    category: "General",
  },
  {
    id: 3,
    title: "Bl 1003",
    excerpt: "## Why use react.js {#Why-use-react.js}\n\n**_1.Reusable Components:_**\n\nReact provides a component based structure.Each t...",
    date: "2025-01-01",
    readTime: "10 min read",
    category: "General",
  },
  {
    id: 4,
    title: "Bl 1004",
    excerpt: "## Global vs Local Scope {#Global-vs-Local-Scope}\n\n## Async Defer\n\n## Event bubbling capturing\n\n## Event Throtting and d...",
    date: "2025-01-01",
    readTime: "1 min read",
    category: "General",
  },
  {
    id: 5,
    title: "Bl 1005",
    excerpt: "## What is a Promise in JavaScript {#What-is-a-Promise-in-JavaScript}\n\nA Promise is a special JavaScript object. It prod...",
    date: "2025-01-01",
    readTime: "3 min read",
    category: "General",
  },
  {
    id: 6,
    title: "Bl 1006",
    excerpt: "## New Features in ES6 {#New-Features-in-ES6}\n\nSome of the new features of javascript introductes in ES6 are:\n\n- The Let...",
    date: "2025-01-01",
    readTime: "12 min read",
    category: "General",
  },
  {
    id: 7,
    title: "Bl 1007",
    excerpt: "## Explain \"hoisting\" {#Explain-hoisting}\n\nHoisting is JavaScript's default behavior of moving all declarations to the t...",
    date: "2025-01-01",
    readTime: "11 min read",
    category: "General",
  },
  {
    id: 8,
    title: "Bl 1008",
    excerpt: "Browser JavaScript execution flow, as well as in Node.js, is based on an event loop. `The event loop concept is very sim...",
    date: "2025-01-01",
    readTime: "5 min read",
    category: "General",
  },
  {
    id: 9,
    title: "Bl 1009",
    excerpt: "## Prototype {#Prototype}\n\n![Prototype](/BL-1009/object-prototype-empty.svg)\n\n**The prototype is an object that is assoc...",
    date: "2025-01-01",
    readTime: "3 min read",
    category: "General",
  },
  {
    id: 10,
    title: "Bl 1010",
    excerpt: "**Visual overview of topics covered in this tutorial**\n\n![Lifecycle](/BL-1010/Lifecycle.png)\n\n## What is the React compo...",
    date: "2025-01-01",
    readTime: "5 min read",
    category: "General",
  },
  {
    id: 11,
    title: "Bl 1011",
    excerpt: "## What is Google Firebase? {#What-is-Google-Firebase}\n\nGoogle Firebase is a Google-backed application development softw...",
    date: "2025-01-01",
    readTime: "9 min read",
    category: "General",
  },
  {
    id: 12,
    title: "Bl 1012",
    excerpt: "## Get started with Tailwind CSS {#Get-started-with-Tailwind-CSS}\n\nTailwind CSS works by scanning all of your HTML files...",
    date: "2025-01-01",
    readTime: "1 min read",
    category: "General",
  },
  {
    id: 13,
    title: "Bl 1013",
    excerpt: "## Introduction {#Introduction}\nAmazon Elastic Compute Cloud (Amazon EC2) is a web service that provides resizable compu...",
    date: "2025-01-01",
    readTime: "10 min read",
    category: "General",
  },
  {
    id: 14,
    title: "Bl 1014",
    excerpt: "## 1. What is an Amazon Machine Image (AMI)?\nAn Amazon Machine Image (AMI) is a template that contains a software config...",
    date: "2025-01-01",
    readTime: "4 min read",
    category: "General",
  },
  {
    id: 15,
    title: "Bl 1015",
    excerpt: "## 1. What is Linux? {#1.-What-is-Linux}\nLinux is an open-source, Unix-like operating system based on the Linux kernel....",
    date: "2025-01-01",
    readTime: "5 min read",
    category: "General",
  },
  {
    id: 16,
    title: "Bl 1016",
    excerpt: "## Why Learn the Linux Command Line? {#Why-Learn-the-Linux-Command-Line}\nBefore diving into the specifics, it\u2019s importan...",
    date: "2025-01-01",
    readTime: "4 min read",
    category: "General",
  },
  {
    id: 17,
    title: "Bl 1017",
    excerpt: "This article is based on static and dynamic IPs concept. A static IP address is an address that does not change even aft...",
    date: "2025-01-01",
    readTime: "6 min read",
    category: "General",
  },
  {
    id: 18,
    title: "Bl 1018",
    excerpt: "## Create Subnets and Allocate IP addresses in an Amazon Virtual Private Cloud (Amazon VPC)\n\n## An overview diagram of a...",
    date: "2025-01-01",
    readTime: "9 min read",
    category: "General",
  },
  {
    id: 19,
    title: "Bl 1019",
    excerpt: "## Introduction\nIn today\u2019s cloud-first world, security is non-negotiable. Amazon Inspector is AWS\u2019s automated security a...",
    date: "2025-01-01",
    readTime: "3 min read",
    category: "General",
  },
  {
    id: 20,
    title: "Bl 1020",
    excerpt: "## What is IAM\n\nIAM is a service that helps securely control access to AWS resources. You can use it to manage access to...",
    date: "2025-01-01",
    readTime: "6 min read",
    category: "General",
  },
  {
    id: 21,
    title: "Bl 1021",
    excerpt: "In today\u2019s rapidly evolving digital landscape, cloud computing has become the backbone of modern businesses. As organiza...",
    date: "2025-01-01",
    readTime: "4 min read",
    category: "General",
  },
  {
    id: 22,
    title: "Bl 1022",
    excerpt: "## Introduction\nManagement and monitoring the resources on AWS is important. It helps in making sure that applications p...",
    date: "2025-01-01",
    readTime: "12 min read",
    category: "General",
  },
  {
    id: 23,
    title: "Bl 1023",
    excerpt: "## Introduction\n\nAs part of your day-to-day administrative task in maintaining your workloads, you want to be able to ef...",
    date: "2025-01-01",
    readTime: "13 min read",
    category: "General",
  },
  {
    id: 24,
    title: "Bl 1024",
    excerpt: "# Amazon Key Management Service (KMS): A Comprehensive Guide with Hands-On Lab\n\nCryptography is the practice of converti...",
    date: "2025-01-01",
    readTime: "11 min read",
    category: "General",
  },
]
