import { useParams, useNavigate } from 'react-router-dom'
import { useEffect, useRef, useState } from 'react'

/**
 * BlogPostPage — renders a pre-built HTML blog post in a full-page iframe.
 *
 * Each .md file in public/blogs/ has a matching .html file generated by
 * convert-blogs.js. This component simply loads that HTML file.
 *
 * The HTML files are fully self-contained (fonts, styles, back navigation)
 * so no markdown parsing or styling is needed here at all.
 */
export default function BlogPostPage() {
  const { id } = useParams()
  const [height, setHeight] = useState('100vh')
  const iframeRef = useRef(null)

  // Resize iframe to match its content height (no scroll bars)
  useEffect(() => {
    const iframe = iframeRef.current
    if (!iframe) return
    const onLoad = () => {
      try {
        const h = iframe.contentDocument?.documentElement?.scrollHeight
        if (h) setHeight(`${h}px`)
      } catch (_) {}
    }
    iframe.addEventListener('load', onLoad)
    return () => iframe.removeEventListener('load', onLoad)
  }, [id])

  useEffect(() => { window.scrollTo(0, 0) }, [id])

  return (
    <div className="min-h-screen bg-white dark:bg-dark-950">
      <iframe
        ref={iframeRef}
        src={`/blogs/${id}.html`}
        title="Blog post"
        style={{ width: '100%', height, border: 'none', display: 'block' }}
        scrolling="no"
      />
    </div>
  )
}